hubspot:
  client-id: client-id-aqui
  redirect-uri: http://localhost:8080/oauth/callback
  scopes: crm.objects.contacts.write%20oauth%20crm.objects.contacts.read
  authorization-url: https://app.hubspot.com/oauth/authorize
  client-secret: client-secret-aqui
  token-url: https://api.hubapi.com/oauth/v1/token
  api-url: https://api.hubapi.com

resilience4j:
  ratelimiter:
    instances:
      hubspotContact:
        limit-for-period: 100
        limit-refresh-period: 10s
        timeout-duration: 500ms
